"""Warm-started FIRE to L-BFGS optimizer for ordinary minimization.

FIRE generates the early accepted steps.  At every accepted geometry a
shadow L-BFGS model records the actual displacement ``s`` and force change
``y``.  When the hysteretic force threshold is satisfied, the same live
history is used immediately by L-BFGS; no trajectory replay or conversion to
ASE's restart format is required.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from ase.optimize.fire import FIRE

from saddlemill.dimertools.lbfgs_dimer import LimitedMemoryInverseHessian

norm = np.linalg.norm


@dataclass
class HybridDecision:
    state: str
    switch_event: str = ""
    history_pairs_at_switch: int = 0


class ForceThresholdController:
    """Two-state FIRE/L-BFGS controller with fmax hysteresis."""

    def __init__(
        self,
        enter_fmax=0.20,
        exit_fmax=0.35,
        enter_stable_steps=3,
        exit_stable_steps=2,
        minimum_history_pairs=3,
        warm_start_history=True,
    ):
        self.enter_fmax = float(enter_fmax)
        self.exit_fmax = float(exit_fmax)
        self.enter_stable_steps = int(enter_stable_steps)
        self.exit_stable_steps = int(exit_stable_steps)
        self.minimum_history_pairs = int(minimum_history_pairs)
        self.warm_start_history = bool(warm_start_history)
        if self.enter_fmax <= 0.0 or self.exit_fmax <= 0.0:
            raise ValueError("FIRELBFGS force thresholds must be > 0")
        if self.exit_fmax < self.enter_fmax:
            raise ValueError("FIRELBFGS exit_fmax must be >= enter_fmax")
        if self.enter_stable_steps < 1 or self.exit_stable_steps < 1:
            raise ValueError("FIRELBFGS stable-step counts must be >= 1")
        if self.minimum_history_pairs < 0:
            raise ValueError("FIRELBFGS minimum_history_pairs must be >= 0")
        self.state = "fire"
        self._enter_count = 0
        self._exit_count = 0

    def force_fire(self, event):
        self.state = "fire"
        self._enter_count = 0
        self._exit_count = 0
        return HybridDecision("fire", str(event), 0)

    def update(self, fmax, history_size):
        fmax = float(fmax)
        history_size = int(history_size)
        if self.state == "fire":
            history_ready = (
                not self.warm_start_history
                or history_size >= self.minimum_history_pairs
            )
            enter = fmax <= self.enter_fmax and history_ready
            self._enter_count = self._enter_count + 1 if enter else 0
            self._exit_count = 0
            if self._enter_count >= self.enter_stable_steps:
                self.state = "lbfgs"
                self._enter_count = 0
                return HybridDecision(
                    "lbfgs", "fire_to_lbfgs", history_size
                )
        else:
            exit_now = fmax >= self.exit_fmax
            self._exit_count = self._exit_count + 1 if exit_now else 0
            self._enter_count = 0
            if self._exit_count >= self.exit_stable_steps:
                self.state = "fire"
                self._exit_count = 0
                return HybridDecision(
                    "fire", "lbfgs_to_fire_threshold", history_size
                )
        return HybridDecision(self.state, "", 0)


class SecantHistoryTracker:
    """Collect L-BFGS secant pairs from steps generated by any optimizer."""

    def __init__(self, history):
        self.history = history
        self.previous_position = None
        self.previous_force = None

    def reset(self, reason):
        self.history.reset(reason)
        self.previous_position = None
        self.previous_force = None

    def observe(self, position, force):
        position = np.asarray(position, dtype=float).reshape(-1)
        force = np.asarray(force, dtype=float).reshape(-1)
        added = False
        if self.previous_position is not None:
            s = position - self.previous_position
            if norm(s) > 1.0e-15:
                # y = gradient_new - gradient_old = force_old - force_new.
                y = self.previous_force - force
                added = self.history.add_pair(s, y)
        self.previous_position = position.copy()
        self.previous_force = force.copy()
        return added


class FIRELBFGS(FIRE):
    """FIRE warm-up followed by no-line-search L-BFGS.

    This optimizer works with ordinary ``Atoms`` and ASE filters, including
    ``FrechetCellFilter``, because it operates through ASE's generalized
    ``optimizable`` coordinate and gradient interface.
    """

    def __init__(
        self,
        atoms,
        restart=None,
        logfile="-",
        trajectory=None,
        maxstep=None,
        fire_dt=0.1,
        fire_dtmax=1.0,
        fire_Nmin=5,
        fire_finc=1.1,
        fire_fdec=0.5,
        fire_astart=0.1,
        fire_fa=0.99,
        lbfgs_memory=10,
        lbfgs_initial_hessian=70.0,
        lbfgs_dynamic_h0=False,
        lbfgs_curvature_epsilon=1.0e-12,
        lbfgs_damping=1.0,
        enter_fmax=0.20,
        exit_fmax=0.35,
        enter_stable_steps=3,
        exit_stable_steps=2,
        minimum_history_pairs=3,
        warm_start_history=True,
        reset_history_on_exit=True,
        **kwargs,
    ):
        if restart is not None:
            raise NotImplementedError(
                "FIRELBFGS restart files are not implemented; use "
                "SaddleMill continuation from the saved structure instead."
            )
        if float(lbfgs_damping) <= 0.0:
            raise ValueError("FIRELBFGS lbfgs_damping must be > 0")
        super().__init__(
            atoms,
            restart=None,
            logfile=logfile,
            trajectory=trajectory,
            dt=float(fire_dt),
            maxstep=maxstep,
            dtmax=float(fire_dtmax),
            Nmin=int(fire_Nmin),
            finc=float(fire_finc),
            fdec=float(fire_fdec),
            astart=float(fire_astart),
            fa=float(fire_fa),
            a=float(fire_astart),
            downhill_check=False,
            **kwargs,
        )
        self.fire_dt_initial = float(fire_dt)
        self.lbfgs_damping = float(lbfgs_damping)
        self.warm_start_history = bool(warm_start_history)
        self.reset_history_on_exit = bool(reset_history_on_exit)
        history = LimitedMemoryInverseHessian(
            memory=int(lbfgs_memory),
            initial_hessian=float(lbfgs_initial_hessian),
            dynamic_h0=bool(lbfgs_dynamic_h0),
            curvature_epsilon=float(lbfgs_curvature_epsilon),
        )
        self.secant_model = SecantHistoryTracker(history)
        self.controller = ForceThresholdController(
            enter_fmax=enter_fmax,
            exit_fmax=exit_fmax,
            enter_stable_steps=enter_stable_steps,
            exit_stable_steps=exit_stable_steps,
            minimum_history_pairs=minimum_history_pairs,
            warm_start_history=warm_start_history,
        )
        self.last_step_diagnostics = None
        self._diagnostic_serial = 0
        self.switch_count = 0

    @property
    def lbfgs_history(self):
        return self.secant_model.history

    def _reset_fire_state(self):
        self.vel = None
        self.dt = self.fire_dt_initial
        self.a = self.astart
        self.Nsteps = 0

    def _fire_displacement(self, force):
        force = np.asarray(force, dtype=float).reshape(-1)
        if self.vel is None:
            self.vel = np.zeros_like(force)
        else:
            vf = float(np.vdot(force, self.vel))
            f2 = float(np.vdot(force, force))
            if vf > 0.0 and f2 > 0.0:
                v2 = float(np.vdot(self.vel, self.vel))
                self.vel = (
                    (1.0 - self.a) * self.vel
                    + self.a * force / np.sqrt(f2) * np.sqrt(v2)
                )
                if self.Nsteps > self.Nmin:
                    self.dt = min(self.dt * self.finc, self.dtmax)
                    self.a *= self.fa
                self.Nsteps += 1
            else:
                self.vel[:] = 0.0
                self.a = self.astart
                self.dt *= self.fdec
                self.Nsteps = 0
        self.vel += self.dt * force
        step = self.dt * self.vel
        step_norm = float(norm(step))
        clipped = False
        if step_norm > self.maxstep > 0.0:
            step = step * (self.maxstep / step_norm)
            step_norm = float(self.maxstep)
            clipped = True
        return step, step_norm, clipped

    def _clip_step(self, step):
        step = np.asarray(step, dtype=float).reshape(-1)
        metric = float(self.optimizable.gradient_norm(step))
        clipped = False
        if metric > self.maxstep > 0.0:
            step = step * (self.maxstep / metric)
            metric = float(self.maxstep)
            clipped = True
        return step, metric, clipped

    def _lbfgs_displacement(self, force):
        force = np.asarray(force, dtype=float).reshape(-1)
        direction = self.lbfgs_history.apply(force).reshape(-1)
        denom = float(norm(direction) * norm(force))
        alignment = (
            float(np.dot(direction, force) / denom) if denom > 0.0 else -1.0
        )
        if (
            not np.all(np.isfinite(direction))
            or norm(direction) < 1.0e-14
            or float(np.dot(direction, force)) <= 0.0
        ):
            return None, 0.0, False, alignment
        step, step_metric, clipped = self._clip_step(
            self.lbfgs_damping * direction
        )
        return step, step_metric, clipped, alignment

    def step(self, forces=None):
        force = -self._get_gradient(forces)
        force = np.asarray(force, dtype=float).reshape(-1)
        position = np.asarray(self.optimizable.get_x(), dtype=float).reshape(-1)
        fmax = float(self.optimizable.gradient_norm(force))

        state_before = self.controller.state
        if state_before == "lbfgs" or self.warm_start_history:
            self.secant_model.observe(position, force)

        decision = self.controller.update(fmax, self.lbfgs_history.size)
        if decision.switch_event:
            self.switch_count += 1

        if decision.switch_event == "fire_to_lbfgs" and not self.warm_start_history:
            self.secant_model.reset("cold_start_fire_to_lbfgs")
            self.secant_model.observe(position, force)
        elif decision.switch_event == "lbfgs_to_fire_threshold":
            self._reset_fire_state()
            if self.reset_history_on_exit:
                self.secant_model.reset("lbfgs_to_fire_threshold")
                if self.warm_start_history:
                    self.secant_model.observe(position, force)

        active = decision.state
        alignment = ""
        if active == "lbfgs":
            step, step_norm, clipped, alignment = self._lbfgs_displacement(force)
            if step is None:
                self.secant_model.reset("non_descent_lbfgs_direction")
                decision = self.controller.force_fire(
                    "lbfgs_to_fire_non_descent"
                )
                self.switch_count += 1
                self._reset_fire_state()
                if self.warm_start_history:
                    self.secant_model.observe(position, force)
                active = "fire"
                step, step_norm, clipped = self._fire_displacement(force)
            else:
                active = "lbfgs"
        else:
            step, step_norm, clipped = self._fire_displacement(force)

        self.optimizable.set_x(position + step)
        if active == "fire":
            self.dump((self.vel, self.dt))

        self._diagnostic_serial += 1
        history = self.lbfgs_history
        self.last_step_diagnostics = {
            "diagnostic_serial": self._diagnostic_serial,
            "optimizer_step": int(self.nsteps) + 1,
            "active_optimizer": active,
            "switch_event": decision.switch_event,
            "fmax": fmax,
            "step_norm": float(step_norm),
            "step_clipped": int(bool(clipped)),
            "direction_alignment": alignment,
            "warm_start_history": int(self.warm_start_history),
            "history_pairs_at_switch": int(
                decision.history_pairs_at_switch
            ),
            "lbfgs_history_size": int(history.size),
            "lbfgs_pairs_accepted_total": int(history.accepted_pairs_total),
            "lbfgs_pairs_rejected_total": int(history.rejected_pairs_total),
            "lbfgs_history_resets": int(history.reset_count),
            "lbfgs_last_reset_reason": history.last_reset_reason,
            "fire_dt": float(self.dt),
        }

    def hybrid_summary(self):
        history = self.lbfgs_history
        return {
            "final_active_optimizer": self.controller.state,
            "switch_count": int(self.switch_count),
            "lbfgs_history_size": int(history.size),
            "lbfgs_pairs_accepted_total": int(history.accepted_pairs_total),
            "lbfgs_pairs_rejected_total": int(history.rejected_pairs_total),
            "lbfgs_history_resets": int(history.reset_count),
            "lbfgs_last_reset_reason": history.last_reset_reason,
            "warm_start_history": int(self.warm_start_history),
        }
