[Main]
executorlib = True
method = NEB
dir_path = data  # reads all *.traj files recursively in this directory
Optimizer = MDMin
jobs_per_gpu = 1
Calculator = FAIRChemCalculator
fmax = 0.05
steps = 3000

[FAIRChemCalculator]
device = cuda
name_or_path = uma-s-1p2
task_name = omat

[LBFGS]
memory = 10
damping = 0.99
alpha = 200
maxstep = 0.1
use_line_search = False

[MDMin]
dt = 0.05
maxstep = 0.1

[FIRE]
astart = 1
fa = 1
a = 1
dt = 0.03
maxstep = 0.1
dtmax = 0.05
finc = 1.1
fdec = 0.5
downhill_check = False


######################## NEB related ########################
[ourNEB]
only_endpoints_in_input_traj = True
images_location_in_input_traj = 0
relax_endpoints = True
endpoint_relax_Optimizer = LBFGS
endpoint_relax_fmax = 0.02
endpoint_relax_steps = 1000
interpolate_method = ase_linear
num_frames = 10
batch_size = 8

[BaseNEB]
k = 5
method = improvedtangent
climb = True
allow_shared_calculator = True
